import { expect, test } from '@playwright/test';
test('public demo: documented payout, independent replay and practice without a server', async ({ page }) => {
  test.setTimeout(90_000);
  const errors: string[] = []; const apiRequests: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', req => { if (new URL(req.url()).pathname.startsWith('/api/')) apiRequests.push(req.url()); });
  await page.goto('./');
  await expect(page.getByText('Demo sin wallet', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Nueva partida en Testnet', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Ver una partida pagada en Testnet' }).click();
  await expect(page.getByRole('region', { name: 'Ensayo documentado' })).toContainText('Nova recibió 2 XLM');
  await page.screenshot({ path: 'public-test-results/public-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Verificar reproducibilidad' }).click();
  await expect(page.getByText('Replay verificado localmente.')).toBeVisible();
  await page.getByRole('button', { name: 'Probar la arena', exact: true }).click();
  await page.getByLabel('Semilla de la arena').fill('2026');
  await page.getByRole('button', { name: 'Crear nueva partida', exact: false }).click();
  await page.getByRole('button', { name: 'Ejecutar simulación' }).click();
  await expect(page.getByText('Sin premio liquidado.')).toBeVisible({ timeout: 30_000 });
  await page.getByRole('button', { name: 'Verificar reproducibilidad' }).click();
  await expect(page.getByText('Replay verificado localmente.')).toBeVisible();
  const downloaded = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Descargar JSON' }).click();
  expect((await downloaded).suggestedFilename()).toMatch(/arenapay-.*\.json/);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'public-test-results/public-mobile.png', fullPage: true });
  expect(apiRequests).toEqual([]); expect(errors).toEqual([]);
});
